#!/usr/bin/env perl
$str=`ps -o pid,command | grep resque`;
# print $str;
my @array=split(/\n/,$str);
my @r = grep(/Console/,@array);
my @arr=split(/\s+/,@r[0]);
my $pid = @arr[0];

my $kill = `kill -9 $pid`;
print $kill;
`Console/cake CakeResque.CakeResque stop`